require("plugins.plugins")
require("entry")

require("general")
require("plugin-fzf-lua")
require("colorscheme")
require("file-system")
require("status-line")
require("plugin-which-key")
require("bad-habits")
require("lsp")
require("terminal")
require("completion")

require("final")
